name: 'Label pull request'
on:
  pull_request:
    branches:
      - main
      - develop
    types: [opened]
jobs:
  pr-labeler:
    name: 'Auto label the Pull Reqest'
    runs-on: ubuntu-latest
    steps:
      - uses: TimonVS/pr-labeler-action@v3
        with:
          configuration-path: .github/pr-labeler.yml # optional, .github/pr-labeler.yml is the default value
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}