name: Publish to NPM and Github Packages
on:
  push:
    branches:
      - main
jobs:
  publish-to-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node
        uses: actions/setup-node@v2
        with:
          registry-url: https://registry.npmjs.org
          scope: "@redhook"
      - run: yarn install  --immutable --immutable-cache
      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  publish-to-github:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node
        uses: actions/setup-node@v2
        with:
          registry-url: https://npm.pkg.github.com
          scope: "@redhook"
      - run: yarn install  --immutable --immutable-cache
      - name: Publish to Github Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
