name: Code Checks

on:
  pull_request:

jobs:
  code-checks:
    uses: ./.github/workflows/code-checks.yml@v1
    secrets:
      NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}

  publish-beta:
    uses: .github/workflows/publish-beta.yml@v1
    needs: code-checks
    secrets:
      NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
