name: Code Checks

on:
  pull_request:

jobs:
  code-checks:
    uses: ./.github/actions/code-checks
    secrets:
      NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}

  publish-beta:
    uses: ./.github/actions/publish-beta
    needs: code-checks
    secrets:
      NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
