name: Code Checks

on:
  pull_request:

jobs:
  code-checks:
    uses: redhook/eslint-config/.github/actions/code-checks.yml@v1
    secrets:
      NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}

  publish-beta:
    uses: redhook/eslint-config/.github/actions/publish-beta.yml@v1
    needs: code-checks
    secrets:
      NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
